project:
  type: website
  output-dir: "docs"
  
website:
  title: "Disease Surveillance"
  page-footer:
    background: "#000000"
    center: GeoHealth research group
  navbar:
    left:
      - text: "Home"
        href: index.qmd  
      - text: "Surveillance methods"
        href: 21-diseasemapping.qmd         
      - text: "Dengue in Brazil"
        href: 51-denguebrazil-denguetracker.qmd  
      - text: "Communication"
        href: 31-communication.qmd  
      - text: "Data"
        href: 99-data.qmd         
      - text: "Resources"
        href: 99-resources.qmd    
      - text: "People"
        href: 99-people.qmd        

  sidebar:
    - title: "Surveillance methods"
      contents:
        - 21-diseasemapping.qmd   
        - 22-nowcasting.qmd
        - 23-forecasting.qmd 
    - title: "Dengue in Brazil"
      contents:
        - 51-denguebrazil-denguetracker.qmd
        - 52-denguebrazil-info.qmd   
        - 53-denguebrazil-ews.qmd
        - 59-denguebrazil-data.qmd

bibliography: [bibliography-digitaldatasources.bib, bibliography-diseasemapping.bib, bibliography-forecasting.bib, bibliography-nowcasting.bib]

format:
  html:
    page-layout: full
    theme: cosmo
    code-link: true

